const riskData = [
    {
        real: "LX280",
        zrep:"151920",
        brand:"CASTAN",
        description:"CTSlit 10L DR DE",
        warehouses:"4",
        projected:"OOS Risk",
        unrestricted:"224489",
        qi:"0",
        blocked:"0",
        save:"0",
    },
    {
        real: "LX280",
        zrep:"151920",
        brand:"CASTAN",
        description:"CTSlit 10L DR DE",
        warehouses:"4",
        projected:"OOS Risk",
        unrestricted:"224489",
        qi:"0",
        blocked:"0",
        save:"0",
    },
    {
        real: "LX280",
        zrep:"151920",
        brand:"CASTAN",
        description:"CTSlit 10L DR DE",
        warehouses:"4",
        projected:"OOS Risk",
        unrestricted:"224489",
        qi:"0",
        blocked:"0",
        save:"0",
    },
    {
        real: "LX280",
        zrep:"151920",
        brand:"CASTAN",
        description:"CTSlit 10L DR DE",
        warehouses:"4",
        projected:"OOS Risk",
        unrestricted:"224489",
        qi:"0",
        blocked:"0",
        save:"0",
    },
    {
        real: "LX280",
        zrep:"151920",
        brand:"CASTAN",
        description:"CTSlit 10L DR DE",
        warehouses:"4",
        projected:"OOS Risk",
        unrestricted:"224489",
        qi:"0",
        blocked:"0",
        save:"0",
    },
]