export const data = [
    {
        dateTime: "12th Dec-12:00",
        scenarioName:"Weekly Review with Matt",
        type:"OOS Risk",
        ossRisk:"15%",
        mediumRisk:"25%",
        lowRisk:"20%",
        highStockRisk:"10%",
        zrepItem:"LX280",
        description:"CTSlit 10L DR DE",
    },
    {
        dateTime: "",
        scenarioName:"",
        type:"",
        ossRisk:"",
        mediumRisk:"",
        lowRisk:"",
        highStockRisk:"",
        zrepItem:"",
        description:"",
    },
    {
        dateTime: "",
        scenarioName:"",
        type:"",
        ossRisk:"",
        mediumRisk:"",
        lowRisk:"",
        highStockRisk:"",
        zrepItem:"",
        description:"",
    }
]